name: skDragon
author: Sashie
description: Adds DragonTravel hooks, particle effects and emotes to Skript
api-version: 1.13
version: 0.17
main: ud.skript.sashie.skDragonCore
depend: [Skript]
softdepend: [DragonTravel]
commands:
  skdragon:
    description: skDragon's main command
    usage: /skdragon <help|version|particles>
    permission: skdragon.command